### PR TITLE
Update sys

### PR DESCRIPTION
**Pull request by daph**
Noticed the framework was old enough to not have shadowmasks, so took a stab at updating it.

### CODE REVIEW

**Comment by birdybro** [comment]
`assign VGA_DISABLE = 1;` <-- this disables analog video output, it should be assigned to 0.

**Comment by daph** [comment]
> `assign VGA_DISABLE = 1;` <-- this disables analog video output, it should be assigned to 0.

Ah alrighty. Thanks for the catch, fixed it.

**Comment by birdybro** [comment]
Have you tested everything on it?

**Comment by daph** [comment]
I'm able to boot the game, play it, change around video filters and shadow masks, change dip switches, switch between horizontal and vertical video etc. I don't have anything to test VGA out though so that's kinda how `VGA_DISABLE` got glossed over.

There's also `flip` which had to be wired in to get this to build, but it's not exposed via config. It's set to keep the video unflipped.

**Comment by birdybro** [comment]
This game had some issues with timing before as well, try and let it run for like a couple hours and see if the demo mode gets unsynced, something to be wary of.

**Comment by daph** [comment]
I removed the offending file (this is what I get for copying over from template instead of just wholesale replacing sys, which I've now done). As for the timing issues, I assume you're talking about issue #4 so I'm currently letting that run, following the repro steps in the issue.

**Comment by daph** [comment]
I let it run for over 3 hours on demo mode and then went a played a bit. Everything was normal, the turtles reliably fell down the hole so looks like that issue was fixed at some point along the way and remains fixed.

**Comment by dfilskov** [comment]
Latest update made the core out of range on my 60 Hz monitor :(

**Comment by sorgelig** [comment]
Outdated PR

**Pull request closed without merging**
